### Df
POST http://localhost:8080/api/register
Content-Type: application/json

{
    "name": "Osup",
    "username": "Osup",
    "email": "osup@example.com",
    "password": "password123"
}
### Login
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "login": "osup@example.com",
    "password": "password123"
}

### Logout
POST http://localhost:8080/api/logout

### Insert Data
POST http://localhost:8080/api/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDg2MTA4NzcsInJvbGVzIjpbImFkbWluIl0sInVzZXJfaWQiOjJ9.9fToiB0hneQKtcRVeTOutmRn8CKl_t_-ZaKHBTvMAfY
Content-Type: application/json

{
  "title": "hihihihi",
  "content": "kolkol"
}

### Tampilkan semua data post
GET http://localhost:8080/api/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDg2MTA4NzcsInJvbGVzIjpbImFkbWluIl0sInVzZXJfaWQiOjJ9.9fToiB0hneQKtcRVeTOutmRn8CKl_t_-ZaKHBTvMAfY

###
PUT http://localhost:8080/api/dashboard/post/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDg2MTA4NzcsInJvbGVzIjpbImFkbWluIl0sInVzZXJfaWQiOjJ9.9fToiB0hneQKtcRVeTOutmRn8CKl_t_-ZaKHBTvMAfY
Content-Type: application/json

{
  "title": "Jangjawokan",
  "body": "Isi lengkap artikel"
}

###
DELETE http://localhost:8080/api/dashboard/post/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDg2MTA4NzcsInJvbGVzIjpbImFkbWluIl0sInVzZXJfaWQiOjJ9.9fToiB0hneQKtcRVeTOutmRn8CKl_t_-ZaKHBTvMAfY